### PR TITLE
Remove unnecesary #![feature(asm)]

### PR DESCRIPTION
**Pull request by bjorn3**

### CODE REVIEW

**Comment by LucaCappelletti94** [comment]
Thank you @bjorn3

**Comment by bjorn3** [comment]
That was a quick merge :)

**Comment by zommiommy** [comment]
Thanks for the pull request! We are still pretty new to rust, so any help / tips it's very welcome!

**Comment by bjorn3** [comment]
I didn't see anything really bad during a quick skim. You may want to use `cargo fmt` for code formatting though. (Nothing ugly, but the formatting was a bit non-standard at some places)

**Comment by LucaCappelletti94** [comment]
I will look into it! One of the things that's making me crazy is how to properly handle Option and keyword arguments, do you have any suggestions/tutorials to points us towards to try and reduce the number of parameters that we have in some methods?

Thanks!

**Comment by bjorn3** [comment]
Where sensible you could use structs to bundle groups of arguments that are commonly passes together.

**Pull request merged**
